### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Teodelas** [Azure/toketi-iothub-to-cassandra#1]
I'm trying to run the container on ACS (DCOS).  What would the config be for Cassandra there?  The 9042 port isn't listed in the default config and there are several placed to add ports.
teodelas@msft

**Comment by dluc** [comment]
@Teodelas [this guide](https://dcos.io/docs/1.7/usage/tutorials/cassandra/) should help you setting up Cassandra on DC/OS. 9042 is the default port used by Cassandra. Which image are you using to install Cassandra by the way? That might make a difference in terms of configuration settings.

Once you have Cassandra up and running, you can specify the host and port in IoTHub2Cassandra configuration, as described [here](https://github.com/Azure/toketi-iothub-to-cassandra#configuration). Some examples:

```
// Connect to Cassandra hosted on the local machine, default port 9042
cassandra {
  cluster = "localhost"
}
```

```
// Connect to Cassandra hosted on 10.0.0.123, default port 9042
cassandra {
  cluster = "10.0.0.123"
}
```

```
// Connect to Cassandra hosted on the 'cassandra.host', on 12345
cassandra {
  cluster = "cassandra.host:12345"
}
```

Hope this helps, otherwise let me know. If you haven't tried, you can also test the connector locally with Docker Compose.
